# Generated by Django 5.2.7 on 2025-10-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_pendingregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
